# Question:1
Convert a 1D array to a 2D array with 2 rows?

In [1]:
import numpy as np

In [2]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2
How to stack two arrays vertically?

In [3]:
y = np.arange(10).reshape(2,5)
z = np.ones((2,5), dtype=int)
np.vstack((y,z))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3
How to stack two arrays horizontally?

In [4]:
y = np.arange(10).reshape(2,5)
z = np.ones((2,5), dtype=int)
np.hstack((y,z))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4
How to convert an array of arrays into a flat 1d array?

In [5]:
x = np.arange(10).reshape(2,5)
print(x)
np.ravel(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5
How to Convert higher dimension into one dimension?

In [6]:
arr = np.arange(15).reshape(3,5)
np.ravel(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6
Convert one dimension to higher dimension?

In [7]:
arr = np.arange(15)
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7
Create 5x5 an array and find the square of an array?

In [8]:
arr1 = np.arange(25).reshape(5,5)
np.square(arr1)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8
Create 5x6 an array and find the mean?

In [9]:
arr = np.arange(30).reshape(5,6)
np.mean(arr)

14.5

## Question:9
Find the standard deviation of the previous array in Q8?

In [10]:
np.std(arr)

8.65544144839919

## Question:10
Find the median of the previous array in Q8?

In [11]:
np.median(arr)

14.5

## Question:11
Find the transpose of the previous array in Q8?

In [12]:
arr.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12
Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
a = np.random.randint(-10, 30, 16).reshape(4,4)
print(a)
np.sum(np.diagonal(a))

[[ 27  16   9  23]
 [ 20  -6 -10  13]
 [  4  -7   4  26]
 [  4  26  -5  27]]


52

## Question:13
Find the determinant of the previous array in Q12?

In [19]:
np.linalg.det(a)

-438609.00000000035

## Question:14
Find the 5th and 95th percentile of an array?

In [27]:
ar = np.random.randint(0, 20, 10).reshape(2,5)
print(ar)
print(np.percentile(ar, 5))
print(np.percentile(ar, 95))

[[ 6  2  8  9 10]
 [ 7 10  1  7  1]]
1.0
10.0


## Question:15
How to find if a given array has any null values?

In [32]:
narr = np.array([5,7,0,1,5,3,8])
np.any(narr, 0)

True