In [1]:
import numpy as np

In [2]:
x = np.zeros(10)

In [3]:
y = np.arange(10,49)

In [4]:
y.shape

(39,)

In [5]:
y.dtype

dtype('int32')

In [6]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Muhammad Hassan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Muhammad Ha

In [7]:
print(y.ndim)

1


In [8]:
b = np.ones((3,3), dtype=bool)

In [9]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
np.arange(20).reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [11]:
v = np.arange(10)
print(v)
v[::-1]

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
v1 = np.zeros((10))
v1[4]=1
v1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
i = np.identity(3, dtype=int)
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
arr = np.array([1,2,3,4,5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
(arr1>arr2)

array([[ True, False,  True],
       [False,  True, False]])

In [17]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [18]:
np.where(arr%2==1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
arr=np.arange(10)
arr[[5,6,7,8]]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [20]:
a=np.ones((5,5), dtype=int)
a[1:4,1:4]=0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [21]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr2d = np.arange(10).reshape(2,5)
arr2d[0,:]

array([0, 1, 2, 3, 4])

In [24]:
arr2d = np.arange(10).reshape(2,5)
arr2d[1,1]

6

In [25]:
arr2d = np.arange(10).reshape(2,5)
arr2d[:2,2]

array([2, 7])

In [26]:
aa = np.random.randn(100).reshape(10,10)
aa*10
print(np.min(aa))
print(np.max(aa))

-3.442505419791484
2.5690289611342254


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
ab, a_ind, b_ind = np.intersect1d(a,b, return_indices=True)
print(a_ind)
print(b_ind)

[1 5]
[1 5]


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != "Will"]

array([[-1.50717215, -0.09471313,  0.19741641, -0.18741613],
       [ 0.15917032,  1.23841354,  0.11743624,  0.59857294],
       [ 0.31522478,  0.41945492,  1.26103601, -0.22635624],
       [ 0.41268895,  1.00380207,  1.5403083 , -0.76789461],
       [-1.06182546, -0.29475269, -0.63726727, -0.76855117]])

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[(names != "Will") & (names != "Joe")]

array([[ 0.43218162, -0.06745885, -0.96414213, -1.13374037],
       [-0.03660167, -0.54541113,  0.86108677, -0.40603485]])

In [39]:
np.random.uniform(1,16,15).reshape(5,3)

array([[11.88710798, 10.61091602,  5.14416097],
       [14.23135197,  6.02445003,  6.2365621 ],
       [ 7.09869955,  8.95528875,  3.00080323],
       [ 5.70558694, 15.91015443,  2.89856061],
       [10.83297141, 11.59694382, 11.12309148]])

In [42]:
arr = np.random.uniform(1,16,16).reshape(2,2,4)
arr

array([[[14.53246639,  2.35627142, 11.19454189, 13.98139301],
        [ 2.61960953,  5.36582697,  1.82267567,  1.92392936]],

       [[14.590351  , 14.28003075, 13.39857492,  5.66294071],
        [ 1.77604167,  7.44377233,  2.32038318, 15.01762879]]])

In [43]:
np.swapaxes(arr, 0, 1)

array([[[14.53246639,  2.35627142, 11.19454189, 13.98139301],
        [14.590351  , 14.28003075, 13.39857492,  5.66294071]],

       [[ 2.61960953,  5.36582697,  1.82267567,  1.92392936],
        [ 1.77604167,  7.44377233,  2.32038318, 15.01762879]]])

In [64]:
a = np.random.uniform(0, 10, 10)
sqa = np.sqrt(a)
np.where(sqa<0.5, 0, sqa)

array([1.98386569, 1.41037496, 2.58730521, 1.82714836, 2.68244668,
       3.07899436, 0.69088167, 2.79555543, 2.42367075, 0.        ])

In [71]:
a = np.random.randint(12, size=12)
b = np.random.randint(12, size=12)
print(a)
print(b)
np.maximum(a,b)

[10  1  6 10 11 10  4  9  4  5  6  4]
[ 0 11  1  9  5  3 10  1 11 11  9  7]


array([10, 11,  6, 10, 11, 10, 10,  9, 11, 11,  9,  7])

In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
np.sort(unique_names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [82]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
ab, a_ind, b_ind = np.intersect1d(a,b, return_indices=True)
np.delete(a, a_ind)

array([1, 2, 3, 4])

In [90]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray2 = sampleArray[:,:2]
np.hstack((sampleArray2, newColumn.T))

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

In [92]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [98]:
z = np.random.randn(20)*10
np.cumsum(z)

array([12.24855957, 29.44469962, 12.76952538, 22.76066732, 18.97471183,
       14.11355154,  8.00787989,  0.40918663,  5.09880138, 10.9029894 ,
       17.80182015, 33.37214253, 50.49321029, 39.20220158, 26.88045796,
       12.20654735,  6.66318273, 14.73436148, 19.47021261, 25.19760534])